spring.application.name=VoltriverDemo
# logging setting.
logging.pattern.console=[%d{yyyy-HH:mm:ss.SSS}][%-5level][%logger.%method:line%line] [thread: %thread] [time: %d{HH:mm:ss}] - %msg%n
logging.pattern.file=[%d{yyyy-HH:mm:ss.SSS}][%-5level][%logger.%method:line%line] [thread: %thread] [time: %d{HH:mm:ss}] - %msg%n
logging.file.name=C:/DEV/sts4_workspace/VoltriverDemo/log/bmail.log
logging.file.path=C:/DEV/sts4_workspace/VoltriverDemo/log
logging.level.root=info
logging.level.org.springframework==info
logging.level.com.example.demo=debug
logging.logback.rollingpolicy.file-name-pattern=C:/DEV/sts4_workspace/VoltriverDemo/log/VoltriverDemo.%d{yyyy-MM-dd}-%i.log
logging.logback.rollingpolicy.max-history=7

# datasource setting.
#spring.datasource.hikari.driver-class-name=org.postgresql.Driver
#spring.datasource.hikari.jdbc-url=jdbc:postgresql://localhost:5432/bmaildev
#spring.datasource.hikari.username=bmail
#spring.datasource.hikari.password=welcome
#spring.datasource.hikari.pool-name=bmail-pool
#spring.datasource.hikari.connection-timeout=30000
#spring.datasource.hikari.maximum-pool-size=10
#spring.datasource.hikari.minimum-idle=5
#spring.datasource.hikari.idle-timeout=60000


#spring.mail.host=smtp.naver.com
#spring.mail.port=465
#spring.mail.username=neo073
#spring.mail.password=vr1069620!
#spring.mail.properties.mail.smtp.auth=true
#spring.mail.properties.mail.smtp.ssl.enable=true
#spring.mail.properties.mail.smtp.ssl.trust=smtp.naver.com
